# Generated by Django 3.0.8 on 2020-08-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_passwordreset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordreset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nueva Contraseña', 'verbose_name_plural': 'Nueva Contraseñas'},
        ),
    ]
