# Generated by Django 3.0.8 on 2020-08-17 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_digital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='direccion',
        ),
    ]
