# Generated by Django 3.0.8 on 2020-08-17 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200816_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='person_shipment',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='user',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Customer'),
        ),
        migrations.DeleteModel(
            name='PersonShipment',
        ),
    ]
