# Generated by Django 3.0.8 on 2020-08-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200825_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', null=True, verbose_name='Descripción'),
        ),
    ]
